---
title: Tj
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: tech journey
markdown: kramdown
highlighter: pygments
excerpt_separator: "<!--more-->"
paginate: 3
paginate_path: blog/page:num
gems:
- jekyll-paginate
permalink: "/:categories/:title"
